GET http://localhost:3000/posts

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Bill"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmlsbCIsImlhdCI6MTYxOTcxMDQ3MX0.qARnfueLSlwqGd6jkjwXTdjsCwmDQGxXh7spnfJZ4MY
###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmlsbCIsImlhdCI6MTYxOTcxMDQ3MX0.qARnfueLSlwqGd6jkjwXTdjsCwmDQGxXh7spnfJZ4MY"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Bill"
}